#!/usr/bin/env bash

#Autor: María Navarro Velasco
#Descripción: COmprueba si un binario está instalado.
#Entrada: el binario.
#Salida: 0 si está, 1 si no.


f_bin_instalado() { 
if command -v "$1" > /dev/null 2>&1; then 
   return 0
else 
   return 1
fi
}
f_bin_instalado "$1"
